<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ode</string>
	</array>
	<key>name</key>
	<string>XPP ODE</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#.*</string>
					<key>name</key>
					<string>comment.line.xpp</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#</string>
					<key>name</key>
					<string>comment.line.number-sign.xpp</string>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b([0-9]+)?\.[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.float.xpp</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.integer.xpp</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![a-zA-Z])(pi|t)(?![a-zA-Z])</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b^([pbviawntgm][a-z]*)\b</string>
					<key>name</key>
					<string>keyword.xpp</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\*\^\+\-\/]</string>
					<key>name</key>
					<string>keyword.operator.xpp</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![a-zA-Z0-9])(if|only|else|then|set|done)(?![a-zA-Z0-9])</string>
					<key>name</key>
					<string>keyword.control.conditional.xpp</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![a-zA-Z0-9])(OUTPUT|XP|YP|ZP|MAXSTOR|BACK|SMALL|BIG|AXES|TOTAL|DT(MAX|MIN)?|NJMP|T0|TRANS|NMESH|METH|TOLER|BOUND|DELAY|[XY](LO|HI)|[XYZ](MAX|MIN))(?![a-zA-Z0-9])</string>
					<key>name</key>
					<string>keywork.other.xpp</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![a-zA-Z0-9])(heav|sign|ran|besselj|bessely|erf|exp|erfc|normal|max|delay|ceil|sum|of|sin|cos|tan|sinh|cosh|tanh)(?![a-zA-Z0-9])</string>
					<key>name</key>
					<string>keyword.other.reservedFunctions.xpp</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.xpp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.xpp</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b((d[a-zA-Z]+\/dt))\b</string>
					<key>name</key>
					<string>variable.language.derivative.xpp</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^[a-zA-Z_]+'</string>
					<key>name</key>
					<string>variable.language.derivative.variate.xpp</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.xpp</string>
	<key>uuid</key>
	<string>443580d1-b8be-431d-aa89-2fd08b5f7853</string>
</dict>
</plist>
